apiVersion: v1
kind: ReplicationController
metadata:
  name: onos
spec:
  replicas: 1
  # selector identifies the set of pods that this
  # replication controller is responsible for managing
  selector:
    name: onos
  # template defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        name: onos
        cluster: west-coast
    spec:
      containers:
        - name: onos
          image: ciena/onosms:1.3
          env:
            # User name and password base64 encoded
            - name: KUBE_USER
              value: dmFncmFudA==
            - name: KUBE_PASSWORD
              value: dmFncmFudA==
          ports:
            - containerPort: 8181
              protocol: TCP
              name: api
